## Single LMDB Subdataset

In [1]:

import torch
from torch.utils.data import DataLoader, ConcatDataset
import pyxis.torch as pxt


In [6]:
data_dir = "../dataset/processed"
subset_dir = "ratings_3_100/train/1_of_4"
sub_dataset = pxt.TorchDataset(os.path.join(data_dir, subset_dir))

print(len(sub_dataset))
print(sub_dataset)

44689
pyxis.Reader
Location:		'../dataset/processed/ratings_3_100/train/1_of_4'
Number of samples:	44689
Data keys (0th sample):
	'head_ids' <- dtype: int32, shape: (100,)
	'midtail_ids' <- dtype: int32, shape: (100,)
	'attention_masks' <- dtype: bool, shape: (100,)


## Multiple LMDB ConcatDataset

### Train set

In [8]:

train_data_dir = "../dataset/processed/comments_3_100/val"

# We should filter out only directory name excluding all the *.tar.gz files
subset_list = [subset_dir for subset_dir in os.listdir(train_data_dir) if os.path.isdir(os.path.join(train_data_dir, subset_dir))]
print('Available Chunk list:', subset_list)

full_dataset =  ConcatDataset([pxt.TorchDataset(os.path.join(train_data_dir, subset_dir)) for subset_dir in subset_list])
print('Full Dataset Len:', len(full_dataset))

Available Chunk list: ['4_of_16', '7_of_16', '5_of_16', '8_of_16', '1_of_16', '10_of_16', '11_of_16', '3_of_16', '2_of_16', '13_of_16', '14_of_16', '6_of_16', '16_of_16', '9_of_16', '12_of_16', '15_of_16']
Full Dataset Len: 3943857


### Validation Set

In [8]:

train_data_dir = "../dataset/processed/ratings_3_100/val"

# We should filter out only directory name excluding all the *.tar.gz files
subset_list = [subset_dir for subset_dir in os.listdir(train_data_dir) if os.path.isdir(os.path.join(train_data_dir, subset_dir))]
print('Available Chunk list:', subset_list)

full_dataset =  ConcatDataset([pxt.TorchDataset(os.path.join(train_data_dir, subset_dir)) for subset_dir in subset_list])
print('Full Dataset Len:', len(full_dataset))

Available Chunk list: ['3_of_4', '4_of_4', '2_of_4', '1_of_4']
Full Dataset Len: 19869


In [15]:
full_dataloader = DataLoader(full_dataset, batch_size=128, shuffle=True, num_workers=4)
for batch in full_dataloader:
    print("keys: ", batch.keys())

    print(batch['head_ids'])
    print(batch['head_ids'].shape)

    print(batch['midtail_ids'][0])
    print(batch['midtail_ids'].shape)

    print(batch['attention_masks'])
    print(batch['attention_masks'].shape)

    

    break

keys:  dict_keys(['head_ids', 'midtail_ids', 'attention_masks'])
tensor([[    1,   209,  5377,  ...,     0,     0,     0],
        [    1,   483, 12484,  ...,     0,     0,     0],
        [    1,   379,  9798,  ...,     0,     0,     0],
        ...,
        [    1,   549, 14212,  ...,     0,     0,     0],
        [    1,   237,  6106,  ...,     0,     0,     0],
        [    1,   360,  9303,  ...,     0,     0,     0]], dtype=torch.int32)
torch.Size([128, 100])
tensor([-100,  246,  225,  190,  253,    0,   29,  337,    2,  561,  561,    0,
           0,  565,    1,    0,  365,  130,  225,    0,   29,  561,  581,  521,
           0,    0,  569,  533,    0,  521,  337,  569,  253,    0,   78,   29,
           5,   30,  561,    0,    1,  569,    1,    0, -100, -100, -100, -100,
        -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
        -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
        -100, -100, -100, -100, -100, -100, -100, -

In [13]:
answer_label = batch['midtail_ids']
print(answer_label)
print(torch.sum(answer_label != -100).item())

answer_label[answer_label==0]=-100
print(torch.sum(answer_label != -100).item())



tensor([[-100,  522,  365,  ..., -100, -100, -100],
        [-100,  561,  533,  ..., -100, -100, -100],
        [-100,  561,  117,  ..., -100, -100, -100],
        ...,
        [-100,  569,  561,  ..., -100, -100, -100],
        [-100,  190,  253,  ..., -100, -100, -100],
        [-100,    1,   29,  ...,  141,    0, -100]], dtype=torch.int32)
4791
3535


In [14]:
batch['midtail_ids'][0]

tensor([-100,  522,  365,  513,  513, -100,   78,    5, -100,  225,  141,  533,
        -100,    2,  365,  509, -100,  513, -100,  185,  365,   29, -100,  365,
         133,  117, -100,  132, -100,   26,   21,    1, -100, -100,    1,  521,
         561, -100,  365, -100,  366, -100,  373,  189,    1, -100, -100, -100,
        -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
        -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
        -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
        -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
        -100, -100, -100, -100], dtype=torch.int32)