## Single LMDB Subdataset

In [4]:

import torch
from torch.utils.data import DataLoader, ConcatDataset
import pyxis.torch as pxt


In [6]:
data_dir = "../dataset/processed"
subset_dir = "ratings_3_100/train/1_of_4"
sub_dataset = pxt.TorchDataset(os.path.join(data_dir, subset_dir))

print(len(sub_dataset))
print(sub_dataset)

44689
pyxis.Reader
Location:		'../dataset/processed/ratings_3_100/train/1_of_4'
Number of samples:	44689
Data keys (0th sample):
	'head_ids' <- dtype: int32, shape: (100,)
	'midtail_ids' <- dtype: int32, shape: (100,)
	'attention_masks' <- dtype: bool, shape: (100,)


## Multiple LMDB ConcatDataset

### Train set

In [7]:

train_data_dir = "../dataset/processed/ratings_3_100/train"

# We should filter out only directory name excluding all the *.tar.gz files
subset_list = [subset_dir for subset_dir in os.listdir(train_data_dir) if os.path.isdir(os.path.join(train_data_dir, subset_dir))]
print('Available Chunk list:', subset_list)

full_dataset =  ConcatDataset([pxt.TorchDataset(os.path.join(train_data_dir, subset_dir)) for subset_dir in subset_list])
print('Full Dataset Len:', len(full_dataset))

Available Chunk list: ['1_of_4', '4_of_4', '3_of_4', '2_of_4']
Full Dataset Len: 178780


### Validation Set

In [8]:

train_data_dir = "../dataset/processed/ratings_3_100/val"

# We should filter out only directory name excluding all the *.tar.gz files
subset_list = [subset_dir for subset_dir in os.listdir(train_data_dir) if os.path.isdir(os.path.join(train_data_dir, subset_dir))]
print('Available Chunk list:', subset_list)

full_dataset =  ConcatDataset([pxt.TorchDataset(os.path.join(train_data_dir, subset_dir)) for subset_dir in subset_list])
print('Full Dataset Len:', len(full_dataset))

Available Chunk list: ['3_of_4', '4_of_4', '2_of_4', '1_of_4']
Full Dataset Len: 19869


In [9]:
full_dataloader = DataLoader(full_dataset, batch_size=128, shuffle=True, num_workers=4)
for batch in full_dataloader:
    print("keys: ", batch.keys())

    print(batch['head_ids'])
    print(batch['head_ids'].shape)

    print(batch['midtail_ids'])
    print(batch['midtail_ids'].shape)

    print(batch['attention_masks'])
    print(batch['attention_masks'].shape)

    

    break

keys:  dict_keys(['head_ids', 'midtail_ids', 'attention_masks'])
tensor([[    1,   203,  5213,  ...,     0,     0,     0],
        [    1,   385,  9935,  ...,     0,     0,     0],
        [    1,   483, 12483,  ...,     0,     0,     0],
        ...,
        [    1,   509, 13178,  ...,     0,     0,     0],
        [    1,   496, 12828,  ...,     0,     0,     0],
        [    1,   483, 12483,  ..., 12639, 12171,     2]], dtype=torch.int32)
torch.Size([128, 100])
tensor([[-100,  522,  365,  ..., -100, -100, -100],
        [-100,  561,  533,  ..., -100, -100, -100],
        [-100,  561,  117,  ..., -100, -100, -100],
        ...,
        [-100,  569,  561,  ..., -100, -100, -100],
        [-100,  190,  253,  ..., -100, -100, -100],
        [-100,    1,   29,  ...,  141,    0, -100]], dtype=torch.int32)
torch.Size([128, 100])
tensor([[ True,  True,  True,  ..., False, False, False],
        [ True,  True,  True,  ..., False, False, False],
        [ True,  True,  True,  ..., False, Fals

In [10]:
answer_label = batch['midtail_ids']
print(answer_label)
torch.sum(answer_label != -100).item())


tensor([[-100,  522,  365,  ..., -100, -100, -100],
        [-100,  561,  533,  ..., -100, -100, -100],
        [-100,  561,  117,  ..., -100, -100, -100],
        ...,
        [-100,  569,  561,  ..., -100, -100, -100],
        [-100,  190,  253,  ..., -100, -100, -100],
        [-100,    1,   29,  ...,  141,    0, -100]], dtype=torch.int32)
