## Single LMDB Subdataset

In [1]:

import torch
from torch.utils.data import DataLoader, ConcatDataset
import pyxis.torch as pxt


In [2]:
data_dir = "../dataset/processed"
subset_dir = "ratings_3_100/train/1_of_1"
sub_dataset = pxt.TorchDataset(os.path.join(data_dir, subset_dir))

print(len(sub_dataset))
print(sub_dataset)

158922
pyxis.Reader
Location:		'../dataset/processed/ratings_3_100/train/1_of_1'
Number of samples:	158922
Data keys (0th sample):
	'head_ids' <- dtype: int32, shape: (100,)
	'midtail_ids' <- dtype: int32, shape: (100,)
	'attention_masks' <- dtype: bool, shape: (100,)


## Multiple LMDB ConcatDataset

### Train set

In [3]:

train_data_dir = "../dataset/processed/ratings_3_100/train"

# We should filter out only directory name excluding all the *.tar.gz files
subset_list = [subset_dir for subset_dir in os.listdir(train_data_dir) if os.path.isdir(os.path.join(train_data_dir, subset_dir))]
print('Available Chunk list:', subset_list)

full_dataset =  ConcatDataset([pxt.TorchDataset(os.path.join(train_data_dir, subset_dir)) for subset_dir in subset_list])
print('Full Dataset Len:', len(full_dataset))

Available Chunk list: ['1_of_1']
Full Dataset Len: 158922


### Validation Set

In [5]:

train_data_dir = "../dataset/processed/ratings_3_100/val"

# We should filter out only directory name excluding all the *.tar.gz files
subset_list = [subset_dir for subset_dir in os.listdir(train_data_dir) if os.path.isdir(os.path.join(train_data_dir, subset_dir))]
print('Available Chunk list:', subset_list)

full_dataset =  ConcatDataset([pxt.TorchDataset(os.path.join(train_data_dir, subset_dir)) for subset_dir in subset_list])
print('Full Dataset Len:', len(full_dataset))

Available Chunk list: ['1_of_1']
Full Dataset Len: 39727


In [4]:
full_dataloader = DataLoader(full_dataset, batch_size=128, shuffle=True, num_workers=4)
for batch in full_dataloader:
    print("keys: ", batch.keys())

    print(batch['head_ids'])
    print(batch['head_ids'].shape)

    print(batch['midtail_ids'])
    print(batch['midtail_ids'].shape)

    print(batch['attention_masks'])
    print(batch['attention_masks'].shape)

    

    break

keys:  dict_keys(['head_ids', 'midtail_ids', 'attention_masks'])
tensor([[    1,   437, 11287,  ...,     0,     0,     0],
        [    1,   418, 10793,  ...,     0,     0,     0],
        [    1,    81,     2,  ...,     0,     0,     0],
        ...,
        [    1,   250,  6425,  ...,     0,     0,     0],
        [    1,   247,  6347,  ...,     0,     0,     0],
        [    1,   478, 12353,  ...,     0,     0,     0]], dtype=torch.int32)
torch.Size([128, 100])
tensor([[-100,   22,  113,  ..., -100, -100, -100],
        [-100,  117,    5,  ..., -100, -100, -100],
        [-100,    0, -100,  ..., -100, -100, -100],
        ...,
        [-100,  113,  365,  ..., -100, -100, -100],
        [-100,    1,  365,  ..., -100, -100, -100],
        [-100,  561,  113,  ..., -100, -100, -100]], dtype=torch.int32)
torch.Size([128, 100])
tensor([[ True,  True,  True,  ..., False, False, False],
        [ True,  True,  True,  ..., False, False, False],
        [ True,  True,  True,  ..., False, Fals