## Single LMDB Subdataset

In [9]:

import torch
from torch.utils.data import DataLoader, ConcatDataset
import pyxis.torch as pxt


In [10]:
data_dir = "../dataset/processed"
subset_dir = "ratings_3_100/1_of_1"
sub_dataset = pxt.TorchDataset(os.path.join(data_dir, subset_dir))

print(len(sub_dataset))
print(sub_dataset)

198649
pyxis.Reader
Location:		'../dataset/processed/ratings_3_100/1_of_1'
Number of samples:	198649
Data keys (0th sample):
	'head_ids' <- dtype: int32, shape: (100,)
	'midtail_ids' <- dtype: int32, shape: (100,)
	'attention_masks' <- dtype: bool, shape: (100,)


## Multiple LMDB ConcatDataset

In [15]:

data_dir = "../dataset/processed/ratings_3_100/"

# We should filter out only directory name excluding all the *.tar.gz files
subset_list = [subset_dir for subset_dir in os.listdir(data_dir) if os.path.isdir(os.path.join(data_dir, subset_dir))]
print('Available Chunk list:', subset_list)

full_dataset =  ConcatDataset([pxt.TorchDataset(os.path.join(data_dir, subset_dir)) for subset_dir in subset_list])
print('Full Dataset Len:', len(full_dataset))

Available Chunk list: ['1_of_1']
Full Dataset Len: 198649


In [12]:
full_dataloader = DataLoader(full_dataset, batch_size=128, shuffle=True, num_workers=4)
for batch in full_dataloader:
    print("keys: ", batch.keys())

    print(batch['head_ids'])
    print(batch['head_ids'].shape)

    print(batch['midtail_ids'])
    print(batch['midtail_ids'].shape)

    print(batch['attention_masks'])
    print(batch['attention_masks'].shape)

    

    break

keys:  dict_keys(['head_ids', 'midtail_ids', 'attention_masks'])
tensor([[    1,   490, 12665,  ...,     0,     0,     0],
        [    1,   496, 12831,  ...,     0,     0,     0],
        [    1,   203,  5222,  ...,     0,     0,     0],
        ...,
        [    1,   237,  6106,  ...,     0,     0,     0],
        [    1,   195,  5002,  ...,     0,     0,     0],
        [    1,   206,  5291,  ...,     0,     0,     0]], dtype=torch.int32)
torch.Size([128, 100])
tensor([[-100,  257,  117,  ..., -100, -100, -100],
        [-100,  190,  253,  ..., -100, -100, -100],
        [-100,   29,  565,  ..., -100, -100, -100],
        ...,
        [-100,    5,    0,  ..., -100, -100, -100],
        [-100,   17,  246,  ..., -100, -100, -100],
        [-100,  285,    7,  ..., -100, -100, -100]], dtype=torch.int32)
torch.Size([128, 100])
tensor([[ True,  True,  True,  ..., False, False, False],
        [ True,  True,  True,  ..., False, False, False],
        [ True,  True,  True,  ..., False, Fals